import "@/styles/index.css";
import { Provider } from "jotai";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// 375*812 (ios) 크기.

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Provider>
        <body>
          <div className="container">{children}</div>
        </body>
      </Provider>
    </html>
  );
}
